services:
  backend:
    build: ./Nicebar/backend
    ports:
      - "5000:5000" 
    networks:
      - nicebar_network
    environment:
    - MONGO_URI=${MONGO_URI}
    - SESSION_SECRET=${SESSION_SECRET}
    - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    - ADMIN_SECRET_KEY=${ADMIN_SECRET_KEY}
    - GEMINI_API_KEY=${GEMINI_API_KEY}
    - PORT=${PORT}
    volumes:
      - ./Nicebar/backend:/app       
      - /app/node_modules

  frontend:
    build: ./Nicebar/frontend
    ports:
      - "5173:5173"  
    networks:
      - nicebar_network
    environment:
      VITE_API_URL: http://localhost:5000 
    volumes:
      - ./Nicebar/frontend:/app
      - /app/node_modules  

networks:
  nicebar_network:
    driver: bridge 