services:
  backend:
    build: ./Nicebar/backend
    ports:
      - "5000:5000" 
    networks:
      - nicebar_network
    environment:
      MONGO_URI: mongodb+srv://szymongrzegorzadamczyk_db_user:lWBvTNTB7cLpE9jT@nicebar.t7hjoll.mongodb.net/nicebar?appName=NiceBar
      SESSION_SECRET: twoj_dlugi_sekretny_klucz
    volumes:
      - ./Nicebar/backend:/app       
      - /app/node_modules

  frontend:
    build: ./Nicebar/frontend
    ports:
      - "5173:5173"  
    networks:
      - nicebar_network
    environment:
      VITE_API_URL: http://localhost:5000 
    volumes:
      - ./Nicebar/frontend:/app
      - /app/node_modules  

networks:
  nicebar_network:
    driver: bridge 